antonexe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404

handler404 = "main.views.handler404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views
from antonexe.feeds import BlogRSS

app_name = "main"
urlpatterns = [
    path('',                 views.IndexView.as_view(),    name='index'),
    path('sociallinks/',      views.SocialLinks.as_view(),  name='sociallinks'),
    path('sociallinks.html/', views.SocialLinks.as_view(),  name='sociallinks_redundancy'),
    path('blog.xml/',         BlogRSS(),                    name='blogrss'),
    path('blog/',             views.BlogListView.as_view(), name='bloglist'),
    path('blog/<str:pk>/',    views.BlogPostView.as_view(), name='blogpost'),
    path('<str:pk>/',         views.TextPageView.as_view(), name='textpage'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class TextPage(models.Model):
    url_path = models.CharField(max_length=200, unique=True, primary_key=True)
    title = models.CharField(max_length=100)
    javascript = models.TextField(blank=True)

    def __str__(self):
        return self.title + " (" + self.url_path + ")"
    
    def get_absolute_url(self):
        return reverse('main:textpage', kwargs={'pk': self.url_path})

class TextPageSection(models.Model):
    page = models.ForeignKey(TextPage, on_delete=models.CASCADE)
    heading = models.CharField(max_length=100, blank=True)
    content = models.TextField()
    index = models.IntegerField(default=0)

    def __str__(self):
        return self.heading

    class Meta:
        ordering = ["index"] 

class BlogPost(models.Model):
    url_path = models.CharField(max_length=200, unique=True, primary_key=True, default=timezone.now().strftime("%Y-%m-%d"))

    title = models.CharField(max_length=200)
    creation_date = models.DateTimeField(default=timezone.now)
    author = models.CharField(max_length=100)

    content = models.TextField()

    def __str__(self):
        return self.title + " (" + self.url_path + ")"

    def get_absolute_url(self):
        return reverse('main:blogpost', kwargs={'pk': self.url_path})
    
    class Meta:
        ordering = ["creation_date"]

class SocialMediaGroup(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class SocialMediaLink(models.Model):
    icon = models.TextField()
    name = models.CharField(max_length=50)
    link = models.CharField(max_length=200)

    group = models.ForeignKey(SocialMediaGroup, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]

class NavbarButton(models.Model):
    text = models.CharField(max_length=50)
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.text

class NavbarDropdown(models.Model):
    text = models.CharField(max_length=50)
    
    def __str__(self):
        return self.text

class NavbarDropdownItem(models.Model):
    text = models.CharField(max_length=50)
    link = models.CharField(max_length=200)
    index = models.IntegerField(default=0)

    dropdown = models.ForeignKey(NavbarDropdown, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ["index"] 

main/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import TextPage, BlogPost, SocialMediaGroup, NavbarButton, NavbarDropdown

def handler404(request, exception):
    template_name: str = "main/TextPage.html"

    page = TextPage.objects.get(url_path="404")
    context = {
        "sections": page.textpagesection_set.all(),
        "page": page,
        "navbar_buttons": NavbarButton.objects.all(),
        "navbar_dropdowns": NavbarDropdown.objects.all(),
    }
    return render(request, template_name, context, status=404)

class IndexView(generic.TemplateView):
    template_name: str = "main/TextPage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = TextPage.objects.get(url_path="index")
        context["sections"] = page.textpagesection_set.all()
        context["page"] = page

        context["navbar_buttons"] = NavbarButton.objects.all()
        context["navbar_dropdowns"] = NavbarDropdown.objects.all()

        return context

class TextPageView(generic.TemplateView):
    template_name: str = "main/TextPage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = get_object_or_404(TextPage, url_path=self.kwargs.get('pk'))
        context["sections"] = page.textpagesection_set.all()
        context["page"] = page

        context["navbar_buttons"] = NavbarButton.objects.all()
        context["navbar_dropdowns"] = NavbarDropdown.objects.all()

        return context

class BlogPostView(generic.TemplateView):
    template_name: str = "main/blogpost.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(BlogPost, url_path=self.kwargs.get('pk'))
        context["post"] = post

        context["navbar_buttons"] = NavbarButton.objects.all()
        context["navbar_dropdowns"] = NavbarDropdown.objects.all()

        return context
    
class BlogListView(generic.TemplateView):
    template_name: str = "main/bloglist.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        posts = BlogPost.objects.order_by("-creation_date")
        context["posts"] = posts

        context["navbar_buttons"] = NavbarButton.objects.all()
        context["navbar_dropdowns"] = NavbarDropdown.objects.all()

        return context

class SocialLinks(generic.TemplateView):
    template_name: str = "main/sociallinks.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        groups = SocialMediaGroup.objects.all()

        context["groups"] = groups

        context["navbar_buttons"] = NavbarButton.objects.all()
        context["navbar_dropdowns"] = NavbarDropdown.objects.all()

        return context

main/templates/main/TextPage.html
<!DOCTYPE html>
<html lang="en-IE">
	<head>
		{% load static %}
		<title>{{ page.title }}</title>
		<link rel="stylesheet" href="{% static 'main/mainstyle.css' %}">
		<link rel="manifest" href="{% static 'main/manifest.json' %}">
			<!-- Meta Info -->
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Anton's website">
			<meta name="author" content="Anton">
			<meta name="keywords" content="Anton.exe, Anton">
			<meta name="theme-color" content="#006400">
			<!-- OpenGraph -->
			<meta content="{{ page.title }}" property="og:title" />
			<meta content="website" property="og:type" />
			<meta content="{% static 'main/mii.png' %}" property="og:image" />
			<meta content="{{ request.build_absolute_uri }}" property="og:url" />
	</head>
	
	<body>
		<header>
			<h1>{{ page.title }}</h1>
		</header>
		{% include './navbar.html' with buttons=navbar_buttons dropdowns=navbar_dropdowns %}
		{% for section in sections %}
			<section>
				<h2>{{ section.heading }}</h2>
				<p>{{ section.content|safe|linebreaks }}</p>
			</section>
		{% endfor %}
		<script>
			{{ page.javascript|safe }}
		</script>
		{% include './footer.html' %}
	</body>
</html>

main/templates/main/bloglist.html
<!DOCTYPE html>
<html lang="en-IE">
	<head>
		{% load static %}
		<title>anton's blog</title>
		<link rel="stylesheet" href="{% static 'main/mainstyle.css' %}">
		<link rel="manifest" href="{% static 'main/manifest.json' %}">
			<!-- Meta Info -->
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Anton's website">
			<meta name="author" content="Anton">
			<meta name="keywords" content="Anton.exe, Anton">
			<meta name="theme-color" content="#006400">
			<!-- OpenGraph -->
			<meta content="anton's blog" property="og:title" />
			<meta content="website" property="og:type" />
			<meta content="{% static 'main/mii.png' %}" property="og:image" />
			<meta content="{{ request.build_absolute_uri }}" property="og:url" />
	</head>
	
	<body>
		<header>
			<h1>blog posts</h1>
		</header>
		{% include './navbar.html' with buttons=navbar_buttons dropdowns=navbar_dropdowns %}
        {% for post in posts %}
            <section>
                <h2 style="margin-bottom: 0.25em;"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <h4 style="margin: 0;">Posted on: {{ post.creation_date|date:"j M Y" }}</h4>
                <p style="margin-top: 0.25em;">{{ post.content|striptags|truncatewords:30 }}</p>
            </section>
        {% endfor %}
		{% include './footer.html' %}
	</body>
</html>

main/templates/main/blogpost.html
<!DOCTYPE html>
<html lang="en-IE">
	<head>
		{% load static %}
		<title>{{ post.title }}</title>
		<link rel="stylesheet" href="{% static 'main/mainstyle.css' %}">
		<link rel="manifest" href="{% static 'main/manifest.json' %}">
			<!-- Meta Info -->
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Anton's website">
			<meta name="author" content="Anton">
			<meta name="keywords" content="Anton.exe, Anton">
			<meta name="theme-color" content="#006400">
			<!-- OpenGraph -->
			<meta content="{{ post.title }}" property="og:title" />
			<meta content="article" property="og:type" />
			<meta content="{% static 'main/mii.png' %}" property="og:image" />
			<meta content="{{ request.build_absolute_uri }}" property="og:url" />
			<meta content="{{ post.creation_date|date:'c' }}" property="article:published_time"/>
			<meta content="{{ post.author }}" property="article:author"/>
	</head>
	
	<body>
		<header>
			<h1>blog - {{ post.title }}</h1>
			<h4>Posted on: {{ post.creation_date|date:"j M Y" }}</h4>
		</header>
		{% include './navbar.html' with buttons=navbar_buttons dropdowns=navbar_dropdowns %}
		<section>
			{{ post.content|safe|linebreaks }}
		</section>
		{% include './footer.html' %}
	</body>
</html>

main/templates/main/footer.html
<!DOCTYPE html>
<footer>
	<p>website made with <a rel="noreferrer" href="https://www.djangoproject.com/" target="_blank">django</a> and <a rel="noreferrer" href="https://httpd.apache.org/" target="_blank">apache</a></p>
</footer>

main/templates/main/navbar.html
<!DOCTYPE html>
<div class=navbar>
	{% for button in buttons %}
	<a href="{{button.link}}" target="_top" tabindex="0">{{button.text}}</a>
	{% endfor %}
	{% for dropdown in dropdowns %}
	<div class="dropdown" tabindex="0">
		<button class="dropbtn">
			{{dropdown.text}} ▼
		</button>
		{% for item in dropdown.navbardropdownitem_set.all %}
		<div class="dropdown-content">
			<a href="{{item.link}}" target="_top" tabindex="0">{{item.text}}</a>
		</div>
		{% endfor %}
	</div>
	{% endfor %}
</div>

main/templates/main/sociallinks.html
<!DOCTYPE html>
<html lang="en-IE">
	<head>
		{% load static %}
		<title>social links</title>
		<link rel="stylesheet" href="{% static 'main/mainstyle.css' %}">
		<link rel="manifest" href="{% static 'main/manifest.json' %}">
			<!-- Meta Info -->
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<meta name="description" content="Anton's personal website">
			<meta name="author" content="Anton">
			<meta name="keywords" content="Anton.exe, Anton">
			<meta name="theme-color" content="#006400">
			<!-- OpenGraph -->
			<meta content="social links" property="og:title" />
			<meta content="website" property="og:type" />
			<meta content="{% static 'main/mii.png' %}" property="og:image" />
			<meta content="{{ request.build_absolute_uri }}" property="og:url" />
		<style>
			svg {
				width: 24px;
				height: 24px;
				filter: invert(100%) sepia(0%) saturate(0%) hue-rotate(93deg) brightness(103%) contrast(103%);
			}
			section {
				display: flex;
				flex-wrap: wrap;
			}
			section > div {
				margin: 10px;
				font-size: 24px;
				margin-right: 30px;
			}
			section > div > a {
				color: skyblue;
            }
		</style>
	</head>

    <body>
		<header>
			<h1>social links</h1>
		</header>
		{% include './navbar.html' with buttons=navbar_buttons dropdowns=navbar_dropdowns %}
		<section>
			{% for group in groups %}
			<div>
				<h2>{{ group.title }}</h2>

				{% for link in group.socialmedialink_set.all|dictsort:"name" %}
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="{{ link.icon }}"/></svg>
				<a rel="me" href="{{ link.link }}">{{ link.name }}</a><br>
				{% endfor %}
			</div>
			{% endfor %}
		</section>
		{% include './footer.html' %}
	</body>
</html>